### ISSUE TITLE
Bug on joomla 4.1.2 - Error on article opening

### ISSUE THREAD

**Issue by dpardons** [Tazzios/Universal-buttons#4]
Hi

Error due to "Universal buttons" plugin at opening time of any article on J4.2.1 upgrade:
Joomla 4.2.1
PHP 7.4.29
JCE 2.9.29

Disabling the plugin solves the problem
Regards
Daniel

---------------------------------------
An error has occurred.
Call to undefined method 
Joomla\CMS\Application\AdministratorApplication::isAdmin()              
-----------------------------------                              
Call stack
--
# | Function | Location
1 | () | JROOT\plugins\editors-xtd\universalbuttons\universalbuttons.php:55
2 | plgButtonUniversalButtons->onDisplay() | JROOT\libraries\src\Editor\Editor.php:243
3 | Joomla\CMS\Editor\Editor->getButtons() | JROOT\libraries\src\Editor\Editor.php:100
4 | Joomla\CMS\Editor\Editor->Joomla\CMS\Editor\{closure}() | JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:486
5 | Joomla\Event\Dispatcher->dispatch() | JROOT\plugins\editors\jce\jce.php:262
6 | plgEditorJCE->getXtdButtons() | JROOT\plugins\editors\jce\jce.php:273
7 | plgEditorJCE->displayButtons() | JROOT\plugins\editors\jce\jce.php:183
8 | plgEditorJCE->onDisplay() | JROOT\libraries\src\Editor\Editor.php:196
9 | Joomla\CMS\Editor\Editor->display() | JROOT\libraries\src\Form\Field\EditorField.php:251
10 | Joomla\CMS\Form\Field\EditorField->getInput() | JROOT\libraries\src\Form\FormField.php:471
11 | Joomla\CMS\Form\FormField->__get() | JROOT\libraries\src\Form\Field\TextareaField.php:94
12 | Joomla\CMS\Form\Field\TextareaField->__get() | JROOT\libraries\src\Form\Field\EditorField.php:138
13 | Joomla\CMS\Form\Field\EditorField->__get() | JROOT\libraries\src\Form\Form.php:458
14 | Joomla\CMS\Form\Form->getInput() | JROOT\administrator\components\com_content\tmpl\article\edit.php:72
15 | include() | JROOT\libraries\src\MVC\View\HtmlView.php:410
16 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT\libraries\src\MVC\View\HtmlView.php:203
17 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT\administrator\components\com_content\src\View\Article\HtmlView.php:116
18 | Joomla\Component\Content\Administrator\View\Article\HtmlView->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:639
19 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT\administrator\components\com_content\src\Controller\DisplayController.php:64
20 | Joomla\Component\Content\Administrator\Controller\DisplayController->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:672
21 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:143
22 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:355
23 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:143
24 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:186
25 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:294
26 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:61
27 | require_once()

**Comment by Tazzios** [comment]
Ai, a bad release from my part. :(
`$app->isAdmin()) `
does not exist in J4 anymore. Replacing it with isclient but it is not a one on one replacement and if changed does it workk with j3?
I will look at it this weekend.

**Comment by Tazzios** [comment]
If I understand the docs in this short time of finding a solution.
Quick fix for j4 would be:
universalbutton.php line 55
replace
`isAdmin()`
with
`isClient('administrator')`

**Comment by dpardons** [comment]
Hi
YES, works for J4!
Regards
Daniel

**Comment by Tazzios** [comment]
j4 support added.
